<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Intern\**" />
    <EmbeddedResource Remove="Intern\**" />
    <None Remove="Intern\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNext" Version="5.24.0" />
    <PackageReference Include="DotNext.Threading" Version="5.24.0" />
    <PackageReference Include="MemoryPack" Version="1.21.4" />
    <PackageReference Include="Nerdbank.Streams" Version="2.13.16" />
    <PackageReference Include="NetMQ" Version="4.0.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fast.Messaging.Abstractions\Fast.Messaging.Abstractions.csproj" />
  </ItemGroup>

</Project>
